development:
  dialect: postgres
  database: smsystem
  user: postgres
  password:
  host: localhost
  port: 5432
  pool: 5

test:
  url: postgres://postgres:postgres@127.0.0.1:5432/myapp_test

production:
  url: 'postgres://postgres:postgres@127.0.0.1:5432/myapp_production'
